const guideRoutes = require("./guide.route");
const homeRoutes = require("./home.route");
const enterCodeRoutes = require("./enterCode.route");
const checkCodeRoutes = require("./checkCode.route");
const selectLayoutRoutes = require("./selectLayout.route");
const selectFrameRoutes = require("./selectFrame.route");
const shootRoutes = require("./shoot.route");
const retakeRoutes = require("./retake.route");
const selectImagesRoutes = require("./selectImages.route");
const apiRoutes = require("./api.route");
const saveRoutes = require("./save.route");
const editRoutes = require("./edit.route");
const selectPrintingRoutes = require("./selectPrinting.route");

const editVertiRoutes = require("./editVerti.route");
const editSmallRoutes = require("./editSmall.route");
const editSeason1Routes = require("./editSeason1.route");
const editSeason2Routes = require("./editSeason2.route");
const editSummerRoutes = require("./editSummer.route");
const editDiyRoutes = require("./editDiy.route");
const applyFilterRoutes = require("./applyFilter.route");
const applyStickerRoutes = require("./applySticker.route");
const printingRoutes = require("./printing.route");
module.exports = (app) => {
    app.use("/", homeRoutes);
    app.use("/guide", guideRoutes);
    app.use("/enterCode", enterCodeRoutes);
    app.use("/checkCode", checkCodeRoutes);
    app.use("/select-layout", selectLayoutRoutes);
    app.use("/select-frame", selectFrameRoutes);
    app.use("/shoot", shootRoutes);
    app.use("/retake", retakeRoutes);
    app.use("/select-images", selectImagesRoutes);
    app.use("/api", apiRoutes);
    app.use("/save", saveRoutes);
    app.use("/edit", editRoutes);
    app.use("/select-printing", selectPrintingRoutes);
    app.use("/edit-bigVerti", editVertiRoutes);
    app.use("/edit-small", editSmallRoutes);
    app.use("/edit-season1", editSeason1Routes);
    app.use("/edit-season2", editSeason2Routes);
    app.use("/edit-summer", editSummerRoutes);
    app.use("/edit-diy", editDiyRoutes);
    app.use("/apply-filter", applyFilterRoutes);
    app.use("/apply-sticker", applyStickerRoutes);
    app.use("/printing", printingRoutes);
};
