const homeRoutes = require("./home.route");
const selectLayoutRoutes = require("./selectLayout.route");
const selectFrameRoutes = require("./selectFrame.route");
const shootRoutes = require("./shoot.route");
const retakeRoutes = require("./retake.route");
const apiRoutes = require("./api.route");
const saveRoutes = require("./save.route");
const editRoutes = require("./edit.route");
const selectPrintingRoutes = require("./selectPrinting.route");
const applyStickerRoutes = require("./applySticker.route");
const printingRoutes = require("./printing.route");
module.exports = (app) => {
    app.use("/", homeRoutes);
    app.use("/select-layout", selectLayoutRoutes);
    app.use("/select-frame", selectFrameRoutes);
    app.use("/shoot", shootRoutes);
    app.use("/retake", retakeRoutes);
    app.use("/api", apiRoutes);
    app.use("/save", saveRoutes);
    app.use("/edit", editRoutes);
    app.use("/select-printing", selectPrintingRoutes);
    app.use("/apply-sticker", applyStickerRoutes);
    app.use("/printing", printingRoutes);
};
